### ISSUE TITLE
Escaping spaces

### ISSUE THREAD

**Issue by PitoneMaledetto** [pmcaulay/nagios-plugins#12]
Hi,
thank you for the plugin!
I have an issue where a space in a log file prevents me to read the log.
`Controller_log_2017-12-01 (1).txt`
How can I escape the space while manually testing the plugin via the cmd?

This is the error that I am getting:
`Cannot read 'c:\Users\myuser\Desktop\Controller_log_2017-12-01'`

But if I take the space away and run:
`check_log3.exe -l "c:\Users\myuser\Desktop\Controller_log_2017-12-01(1).txt" -p "Manager comms send failed"`

I get:
`Trailing \ in regex m/\/ at script/check_log3.pl line 896.`

Thank you for your help.
Regards 

p.s. I can't change the log file naming convention unfortunately.

**Comment by pmcaulay** [comment]
Hi,

You have found a bug!  It should be sufficient to just quote the filename if the path has spaces in it.
I've fixed this in the latest version (3.14), can you please try it?

`check_log3.exe -l "C:\Users\myuser\Desktop\Controller_log_2017-12-01 (1).txt" -p "Manager comms send failed"`

Kind regards,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
thank you for your response.

I ran the plugin without specifying the regex and I got a normal behaviour:

`check_log3.exe -l "C:\Users\myuser\Desktop\Controller_log_2017-12-01 (1).txt"`
_Regular expression not specified._

_This is check_log3.exe version 3.14_

_Usage: check_log3.exe [ -v | --version ]_
_Usage: check_log3.exe [ -h | --help ]_
_Usage: check_log3.exe --manual_
_Usage: check_log3.exe --list-encodings_
_Usage: check_log3.exe -l log_file|log_directory (-p pattern [-p pattern ...])|-P patternfile)_
       _[-i] [-n negpattern|-f negpatternfile ] [-s seek_file|seek_base_dir] [--show-filename]_
       _([-m glob-pattern] [-t most_recent|first_match|last_match] [--timestamp=time-spec])_
        _[-d] [-D] [-a] [-C {-|+}n] [-q] [-Q] ([-e '{ eval block }'|-E script_file]|--secure)_
        _([-N|--report-max=N]|[--report-only=N])|([-1|--stop-first-match]|[--report-first-match])_
       _[--ok]|([-w warn_count] [-c crit_count] [--negate])_
        _[--input-enc=encoding] [--output-enc=encoding] [--crlf]_
        _[--missing=STATE [--missing-msg=message]]_

Then with the regex:
`check_log3.exe -l "C:\Users\myuser\Desktop\Controller_log_2017-12-01 (1).txt" -p "Manager comms send failed"`

and I get still:
_Cannot read 'C:\Users\myuser\Desktop\Controller_log_2017-12-01'_

Hope it helps.
Giuseppe

**Comment by pmcaulay** [comment]
Hi,

Interesting -- what version of Windows are you running?  Also, could you please run the plugin with the --debug flag?

Thanks!
Peter

**Comment by pmcaulay** [comment]
Hi,

Never mind, I can reliably reproduce the problem with the EXE but not the interpreted Perl version.  I fear it's a compiler and/or library problem; if you are able, I recommend installing Strawberry Perl on your server until I can fix the EXE version, sorry...

Kind regards,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
thank you for your help and reply.
I have already installed Strawberry Pearl in the test machine where I am running the plugin, shall I run the version of the plugin as if I was on a Linux machine?
I really can't install Strawberry Pearl in all our production servers so I will wait until you will have time to look at the code.
Thank you for your time.
Giuseppe

**Comment by pmcaulay** [comment]
Hi,

Yes, the .pl version works on both Windows and Unix.

I'm rebuilding my Win32 VM now, I'll post an update soonish.

Kind regards,
Peter

**Comment by pmcaulay** [comment]
Hi,

I've pushed a new build of check_log3.exe, can you please try again?

Thanks!
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
apologies for the delay but all the festivities and a load in work stopped me to test the plugin further.
Happy new year by the way :)
Yes! The plugin now works and reads the file with a space in its name.
Thank you very much for the fix.
Regards

**Comment by PitoneMaledetto** [comment]
C:\Users\myuser\Desktop>check_log3.exe -l "c:\Users\myuser\Desktop\test (1).txt" -p "Manager coms send failed"
OK: Found 0 lines (limit=1/0): No matches found.|lines=0

**Comment by PitoneMaledetto** [comment]
Just one last question if you may.
The usual behaviour of checking a log with plugins is that if we find a CRITICAL (matching the given pattern) on the next Nagios check the CRITICAL will be now OK but the application still not running because of that error. How can I stay on CRITICAL until the application is re-started?
I am not sure if I make any sense with my statement above :)

For example:

```
C:\Users\myuser\Desktop>check_log3.exe -l "c:\Users\myuser\Desktop\test (1).txt" -p "Manager coms send failed" -s seek.txt
OK: Found 0 lines (limit=1/0): No matches found.|lines=0

```
I am manually adding the line:

```
C:\Users\myuser\Desktop>check_log3.exe -l "c:\Users\myuser\Desktop\test (1).txt" -p "Manager coms send failed" -s seek.txt
WARNING: Found 1 lines (limit=1/0): Manager coms send failed|lines=1
```

Next check OK but the application still not running so it should be WARNING again.

```
C:\Users\myuser\Desktop>check_log3.exe -l "c:\Users\myuser\Desktop\test (1).txt" -p "Manager coms send failed" -s seek.txt
OK: Found 0 lines (limit=1/0): No matches found.|lines=0
```
maybe if we could not change the position of the seek file for n times? Not sure how to solve this problem.

Thank you for your time.

**Comment by pmcaulay** [comment]
Hi,

That is currently not possible because of the way Nagios works.  The meaning of the service check results are to be interpreted as strictly bound to the check interval, i.e. no error conditions since last check = OK.

To make service states "sticky" you could perhaps add an event handler to your service which, when it goes into a problem state, sends a passive check result to a (different) passive service check to reflect the state of the application.  You will then have to reset that passive service manually.

Kind regards,
Peter

**Comment by pmcaulay** [comment]
Closing since original problem is solved.

**Comment by sastorsl** [comment]
Regarding that the job is OK on the next iteration.
We solve this by sending tickets from icinga to a ticketing system. Operators must close these tickets manually and investigate the logs.
